spring:
  application:
    name: zookeeper_provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo_demo
    username: root
    password: Zwy19931219
    type: com.alibaba.druid.pool.DruidDataSource
dubbo:
  registry:
    address: zookeeper://172.16.108.4:2181
    timeout: 10000
  metadata-report:
    address: zookeeper://172.16.108.4:2181
  protocol:
    name: dubbo
    port: 20880

