spring:
  application:
    name: zookeeper_consumer

dubbo:
  registry:
    address: zookeeper://172.16.108.4:2181
    timeout: 10000
  metadata-report:
    address: zookeeper://172.16.108.4:2181
server:
  port: 8081